name: next-terminal Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  next-terminal_Release:
    name: next-terminal release
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: Private Actions Checkout
        uses: actions/checkout@v4
      - name: node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: npm install
        run: |
          cd web
          npm install --global yarn
          yarn
      - name: go Setup
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build package Linux
        env:
          CI: false
        run: |
          sh build.sh
          mv next-terminal next-terminal-bin
          mkdir next-terminal
          cp next-terminal-bin next-terminal/next-terminal
          cp config.yml.example next-terminal/config.yml
          cp LICENSE next-terminal/
          tar zcvf next-terminal.tar.gz next-terminal/
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: next-terminal.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
